---
- name: "Brew Cask Install: {{ item }}"
  homebrew_cask:
    update_homebrew: no
    name: "{{ item }}"
    state: latest
    accept_external_apps: yes
  when: item not in brew_cask_installed.stdout_lines