---
- name: Check if the Brew package manager exists on system
  command: "brew -v"
  register: brew_state
  ignore_errors: yes

- name: Install Brew package manager
  command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  become: yes
  when: brew_state.rc != 0

- name: Update Brew package manager
  homebrew:
    update_homebrew: yes

- name: Activate brew taps
  include: brew-taps.yml
  with_items: "{{ packages_brew_taps }}"
  when: packages_brew_taps | length > 0

- name: Get a list of installed brew forumla packages
  raw: brew list --formula | tr " " "\n"
  register: brew_formula_installed
  become: no

- name: Get a list of installed brew cask packages
  raw: brew list --cask | tr " " "\n"
  register: brew_cask_installed
  become: no

- name: Install brew packages
  include: brew-packages.yml
  with_items: "{{ packages_brew }}"
  when: packages_brew | length > 0

- name: Install brew cask packages
  include: brew-cask-packages.yml
  with_items: "{{ packages_brew_cask }}"
  when: packages_brew_cask | length > 0

- name: Install brew cask fonts
  include: brew-cask-fonts.yml
  with_items: "{{ packages_brew_cask_fonts }}"
  when: packages_brew_cask_fonts | length > 0
