---
- name: Install docker-machine requirements
  homebrew_cask:
    name: "{{ item }}"
    state: present
    accept_external_apps: yes
  with_items:
    - virtualbox
    - docker-toolbox

- name: Check if docker-machine instance already running in virtualbox
  command: docker-machine ls | grep default | grep virtualbox
  register: docker_machine_state
  ignore_errors: yes

- name: Setup docker-machine instance with virtualbox
  command: docker-machine create -d virtualbox --virtualbox-no-vtx-check --virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/latest/download/boot2docker.iso default
  when: docker_machine_state.rc != 0